################# 리뷰어 전체 조회 ##################
select * 
FROM TB_MEMBER MB JOIN TB_MEMBER_AUTH AU
ON MB.MEMBER_IDX = AU.MEMBER_IDX
JOIN TB_REVIEWER_PROFILE RP
ON MB.MEMBER_IDX = RP.MEMBER_IDX;

############ 리뷰어 채널 전체 조회 #############
select MB.MEMBER_IDX, MB.MEMBER_NAME, RC.INF_TYPE_CODE_ID, RC.CHANNEL_URL
FROM TB_MEMBER MB JOIN TB_MEMBER_AUTH AU
ON MB.MEMBER_IDX = AU.MEMBER_IDX
JOIN TB_REVIEWER_PROFILE RP
ON MB.MEMBER_IDX = RP.MEMBER_IDX
JOIN TB_REVIEWER_CHANNEL RC
ON MB.MEMBER_IDX = RC.MEMBER_IDX;
#################　소상공인　전체　조회 ####################
select * 
FROM TB_MEMBER MB JOIN TB_MEMBER_AUTH AU
ON MB.MEMBER_IDX = AU.MEMBER_IDX
JOIN TB_OWNER_PROFILE OP
ON MB.MEMBER_IDX = OP.MEMBER_IDX;

