// src/api/campaigns.js (더미 → 추후 백엔드 연동)
// ───────────────────────────────────────────────
export async function getPremiumCampaigns() {
// TODO: 실제 API로 교체: return (await fetch('/api/campaigns?premium=true&limit=8')).json();
return [
{
campaignIdx: 101,
title: "[재택] LG전자 휘센 오브제컬렉션 제습기",
subtitle: "LG전자 휘센 오브제컬렉션 제습기 에센스 화이트 15L",
thumbnailUrl: "https://images.unsplash.com/photo-1604339455633-43f4013d24db?q=80&w=1600&auto=format&fit=crop",
campaignTypeName: "배송형(온라인)",
categoryName: "디지털",
channelName: "블로그",
region: null,
applicants: 8642,
applyLimit: 1,
daysLeft: 1,
likes: 0,
rewardPoint: 0,
rewardLabel: "제품 무상 제공",
badgeLeft: [{ text: "리뷰노트", tone: "green" }],
},
{
campaignIdx: 102,
title: "[재택] 석고방향제 1위 '르마'",
subtitle: "르마베이커 베이비돌",
thumbnailUrl: "https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1600&auto=format&fit=crop",
campaignTypeName: "배송형(온라인)",
categoryName: "기타",
channelName: "블로그",
region: null,
applicants: 911,
applyLimit: 100,
daysLeft: 1,
likes: 0,
rewardPoint: 52100,
rewardLabel: "포인트",
badgeLeft: [{ text: "핫딜노트", tone: "red" }],
},
{
campaignIdx: 103,
title: "[충남/보령시] 마니마니조개구이",
subtitle: "자유 식사권 16만원 + 10만 포인트",
thumbnailUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1600&auto=format&fit=crop",
campaignTypeName: "방문형(오프라인)",
categoryName: "맛집",
channelName: "유튜브",
region: "보령시",
applicants: 171,
applyLimit: 3,
daysLeft: 4,
likes: 0,
rewardPoint: 1000000,
rewardLabel: "1,000,000 P",
badgeLeft: [{ text: "프리미엄", tone: "blue" }],
},
{
campaignIdx: 104,
title: "[충남/예산군] 낙원숯불갈비",
subtitle: "식사권 100,000원 + 300,000P",
thumbnailUrl: "https://images.unsplash.com/photo-1604908554041-1c7f4b7332c7?q=80&w=1600&auto=format&fit=crop",
campaignTypeName: "방문형(오프라인)",
categoryName: "맛집",
channelName: "릴스",
region: "예산군",
applicants: 72,
applyLimit: 1,
daysLeft: 7,
likes: 0,
rewardPoint: 300000,
rewardLabel: "300,000 P",
badgeLeft: [{ text: "프리미엄", tone: "blue" }],
},
];
}