// src/api/campaigns.js (더미 → 추후 백엔드 연동)
// ───────────────────────────────────────────────
export async function getPremiumCampaigns() {
  // TODO: 실제 API로 교체
  // return (await fetch('/api/campaigns?premium=true&limit=8')).json();

  return [
    {
      campaignIdx: 101,
      title: "[재택] LG전자 휘센 오브제컬렉션 제습기",
      subtitle: "LG전자 휘센 오브제컬렉션 제습기 에센스 화이트 15L",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1604339455633-43f4013d24db?q=80&w=1600&auto=format&fit=crop",
      campaignTypeName: "배송형(온라인)",
      categoryName: "디지털",
      channelName: "블로그",
      region: null,
      applicants: 8642,
      applyLimit: 1,
      daysLeft: 1,
      likes: 0,
      rewardPoint: 0,
      rewardLabel: "제품 무상 제공",
      badgeLeft: [{ text: "리뷰노트", tone: "green" }],
    },
    {
      campaignIdx: 102,
      title: "[재택] 석고방향제 1위 '르마'",
      subtitle: "르마베이커 베이비돌",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1600&auto=format&fit=crop",
      campaignTypeName: "배송형(온라인)",
      categoryName: "기타",
      channelName: "블로그",
      region: null,
      applicants: 911,
      applyLimit: 100,
      daysLeft: 1,
      likes: 0,
      rewardPoint: 52100,
      rewardLabel: "포인트",
      badgeLeft: [{ text: "핫딜노트", tone: "red" }],
    },
    {
      campaignIdx: 103,
      title: "[충남/보령시] 마니마니조개구이",
      subtitle: "자유 식사권 16만원 + 10만 포인트",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1600&auto=format&fit=crop",
      campaignTypeName: "방문형(오프라인)",
      categoryName: "맛집",
      channelName: "유튜브",
      region: "보령시",
      applicants: 171,
      applyLimit: 3,
      daysLeft: 4,
      likes: 0,
      rewardPoint: 1000000,
      rewardLabel: "1,000,000 P",
      badgeLeft: [{ text: "프리미엄", tone: "blue" }],
    },
    {
      campaignIdx: 104,
      title: "[충남/예산군] 낙원숯불갈비",
      subtitle: "식사권 100,000원 + 300,000P",
      thumbnailUrl:
        "https://images.unsplash.com/photo-1604908554041-1c7f4b7332c7?q=80&w=1600&auto=format&fit=crop",
      campaignTypeName: "방문형(오프라인)",
      categoryName: "맛집",
      channelName: "릴스",
      region: "예산군",
      applicants: 72,
      applyLimit: 1,
      daysLeft: 7,
      likes: 0,
      rewardPoint: 300000,
      rewardLabel: "300,000 P",
      badgeLeft: [{ text: "프리미엄", tone: "blue" }],
    },
    {
      campaignIdx: 105,
      title: "[재택] 프리미엄 커피머신 체험단",
      subtitle: "가정용 에스프레소 머신",
      thumbnailUrl: "https://images.unsplash.com/photo-1510626176961-4b37d0d4a06b?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "가전",
      channelName: "블로그",
      region: null,
      applicants: 512,
      applyLimit: 20,
      daysLeft: 2,
      likes: 5,
      rewardPoint: 20000,
      rewardLabel: "포인트",
      badgeLeft: [{ text: "신규", tone: "green" }],
    },
    {
      campaignIdx: 106,
      title: "[서울] 뷰티 살롱 헤어케어 체험",
      subtitle: "헤어 트리트먼트 서비스",
      thumbnailUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1600",
      campaignTypeName: "방문형(오프라인)",
      categoryName: "뷰티",
      channelName: "인스타그램",
      region: "서울",
      applicants: 78,
      applyLimit: 5,
      daysLeft: 3,
      likes: 1,
      rewardPoint: 0,
      rewardLabel: "서비스 제공",
      badgeLeft: [{ text: "뷰티", tone: "pink" }],
    },
    {
      campaignIdx: 107,
      title: "[재택] 스마트워치",
      subtitle: "신형 스마트워치 무료 체험",
      thumbnailUrl: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "디지털",
      channelName: "유튜브",
      region: null,
      applicants: 1300,
      applyLimit: 10,
      daysLeft: 6,
      likes: 12,
      rewardPoint: 0,
      rewardLabel: "제품 무상 제공",
      badgeLeft: [{ text: "인기", tone: "orange" }],
    },
    {
      campaignIdx: 108,
      title: "[부산] 프리미엄 호텔 1박 숙박권",
      subtitle: "럭셔리 호텔 숙박 체험",
      thumbnailUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1600",
      campaignTypeName: "방문형(오프라인)",
      categoryName: "여행",
      channelName: "블로그",
      region: "부산",
      applicants: 34,
      applyLimit: 2,
      daysLeft: 2,
      likes: 0,
      rewardPoint: 0,
      rewardLabel: "숙박권 제공",
      badgeLeft: [{ text: "프리미엄", tone: "blue" }],
    },
    {
      campaignIdx: 109,
      title: "[재택] 유기농 간식 세트",
      subtitle: "건강한 유기농 과자와 음료",
      thumbnailUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "식품",
      channelName: "카페",
      region: null,
      applicants: 213,
      applyLimit: 50,
      daysLeft: 5,
      likes: 0,
      rewardPoint: 15000,
      rewardLabel: "포인트",
      badgeLeft: [{ text: "푸드", tone: "green" }],
    },
    {
      campaignIdx: 110,
      title: "[재택] 무선 이어폰 체험단",
      subtitle: "최신 블루투스 이어폰",
      thumbnailUrl: "https://images.unsplash.com/photo-1518444028784-8081fdfb7d4a?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "디지털",
      channelName: "블로그",
      region: null,
      applicants: 950,
      applyLimit: 30,
      daysLeft: 1,
      likes: 2,
      rewardPoint: 0,
      rewardLabel: "제품 무상 제공",
      badgeLeft: [{ text: "인기", tone: "orange" }],
    },
    {
      campaignIdx: 111,
      title: "[제주] 로컬 맛집 투어",
      subtitle: "제주 현지 맛집 쿠폰",
      thumbnailUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1600",
      campaignTypeName: "방문형(오프라인)",
      categoryName: "맛집",
      channelName: "인스타그램",
      region: "제주",
      applicants: 45,
      applyLimit: 5,
      daysLeft: 8,
      likes: 0,
      rewardPoint: 50000,
      rewardLabel: "포인트",
      badgeLeft: [{ text: "여행", tone: "purple" }],
    },
    {
      campaignIdx: 112,
      title: "[재택] 프리미엄 스킨케어",
      subtitle: "고급 스킨케어 세트",
      thumbnailUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "뷰티",
      channelName: "유튜브",
      region: null,
      applicants: 230,
      applyLimit: 10,
      daysLeft: 4,
      likes: 0,
      rewardPoint: 80000,
      rewardLabel: "포인트",
      badgeLeft: [{ text: "뷰티", tone: "pink" }],
    },
    {
      campaignIdx: 113,
      title: "[서울] 프리미엄 스파 이용권",
      subtitle: "도심 속 럭셔리 스파",
      thumbnailUrl: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?q=80&w=1600",
      campaignTypeName: "방문형(오프라인)",
      categoryName: "뷰티",
      channelName: "블로그",
      region: "서울",
      applicants: 90,
      applyLimit: 2,
      daysLeft: 1,
      likes: 0,
      rewardPoint: 0,
      rewardLabel: "서비스 제공",
      badgeLeft: [{ text: "프리미엄", tone: "blue" }],
    },
    {
      campaignIdx: 114,
      title: "[재택] 헬스케어 앱 프리미엄 구독권",
      subtitle: "6개월 무료 구독",
      thumbnailUrl: "https://images.unsplash.com/photo-1590487988827-38aab1c9e90e?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "디지털",
      channelName: "유튜브",
      region: null,
      applicants: 500,
      applyLimit: 100,
      daysLeft: 10,
      likes: 0,
      rewardPoint: 0,
      rewardLabel: "구독권 제공",
      badgeLeft: [{ text: "디지털", tone: "gray" }],
    },
    {
      campaignIdx: 115,
      title: "[재택] 반려동물 사료 세트",
      subtitle: "프리미엄 펫푸드",
      thumbnailUrl: "https://images.unsplash.com/photo-1560807707-8cc77767d783?q=80&w=1600",
      campaignTypeName: "배송형(온라인)",
      categoryName: "반려동물",
      channelName: "블로그",
      region: null,
      applicants: 321,
      applyLimit: 20,
      daysLeft: 12,
      likes: 0,
      rewardPoint: 30000,
      rewardLabel: "포인트",
      badgeLeft: [{ text: "펫", tone: "brown" }],
    },
  ];
}
